<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One answer choice.
 *
 * A wrong option's `misconception_id` is not a guess: the distractor was GENERATED by executing
 * that misconception (see tools/questions/lib.mjs), so choosing it is evidence of that specific
 * error rather than of generic wrongness. That is what the teacher's misconception analytics
 * stands on.
 */
/**
 * @property bool $is_correct
 * @property int $question_id
 * @property int|null $misconception_id
 */
final class QuestionOption extends Model
{
    // No factory, on purpose. Answer options come from content/, which tools/ validates for
    // topological order, cycles and misconception coverage before anything is seeded. A
    // fabricated option in a test would pass against a graph shape the real content can
    // never take, and the test would be proving nothing.

    public $timestamps = false;

    protected $fillable = ['question_id', 'text_ar', 'is_correct', 'misconception_id', 'position'];

    /** @return array<string, string> */
    protected function casts(): array
    {
        return ['is_correct' => 'boolean'];
    }

    /** @return BelongsTo<Question, $this> */
    public function question(): BelongsTo
    {
        return $this->belongsTo(Question::class);
    }

    /** @return BelongsTo<Misconception, $this> */
    public function misconception(): BelongsTo
    {
        return $this->belongsTo(Misconception::class);
    }
}
