<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Engine\DifficultyAction;
use App\Http\Controllers\Concerns\ResolvesStudent;
use App\Http\Controllers\Controller;
use App\Http\Resources\QuestionResource;
use App\Models\Question;
use App\Models\QuestionOption;
use App\Models\Skill;
use App\Models\Student;
use App\Services\ExerciseService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\ValidationException;

final class ExerciseController extends Controller
{
    use ResolvesStudent;

    public function __construct(private readonly ExerciseService $exercises) {}

    /**
     * The whole question bank for one skill, in one response.
     *
     * Not one question at a time: the client needs the skill's items in IndexedDB to practise with
     * the network off, which is the point of the product. Thirty questions is a few kilobytes —
     * far cheaper than thirty round trips a student on 2G will never complete.
     */
    public function bank(Request $request, string $code): JsonResponse
    {
        $this->student();

        $skill = Skill::query()->where('code', $code)->firstOrFail();

        $questions = Question::query()
            ->where('skill_id', $skill->id)
            ->with(['options', 'skill:id,code'])
            ->orderBy('difficulty')
            ->get();

        return response()->json([
            'skill' => [
                'code' => $skill->code,
                'name_ar' => $skill->name_ar,
                'description_ar' => $skill->description_ar,
                'mastery_threshold' => $skill->mastery_threshold,
            ],
            'questions' => QuestionResource::collection($questions),
        ]);
    }

    /** The single next question, for a client that is online and wants the server's choice. */
    public function next(Request $request, string $code): JsonResponse
    {
        $student = $this->student();
        $skill = Skill::query()->where('code', $code)->firstOrFail();

        $decision = $this->exercises->currentDecision($student, $skill);
        $question = $this->exercises->nextQuestion($student, $skill, $decision->difficulty);

        return response()->json([
            'difficulty' => $decision->difficulty->value,
            'question' => $question === null ? null : new QuestionResource($question),
        ]);
    }

    public function answer(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'question_id' => ['required', 'integer', 'exists:questions,id'],
            'option_id' => ['nullable', 'integer', 'exists:question_options,id'],
            'device_id' => ['nullable', 'uuid'],
            'client_seq' => ['nullable', 'integer', 'min:0'],
            'client_created_at' => ['nullable', 'integer', 'min:0'],
        ]);

        $student = $this->student();
        $question = Question::query()->with(['options', 'skill'])->findOrFail($validated['question_id']);

        $option = isset($validated['option_id'])
            ? QuestionOption::query()->with('misconception')->find($validated['option_id'])
            : null;

        if ($option !== null && $option->question_id !== $question->id) {
            throw ValidationException::withMessages([
                'option_id' => 'هذا الخيار لا ينتمي لهذا السؤال.',
            ]);
        }

        $outcome = $this->exercises->submit($student, $question, $option, [
            'device_id' => $validated['device_id'] ?? null,
            'client_seq' => $validated['client_seq'] ?? 0,
            'client_created_at' => $validated['client_created_at'] ?? null,
        ]);

        $decision = $outcome['decision'];
        $skill = $question->skill;

        // Three wrong at the easiest level means the gap is below this skill. Naming the
        // prerequisite here is what turns a dead end into a next step.
        $prerequisite = $decision->action === DifficultyAction::RouteToPrerequisite
            ? $this->exercises->prerequisiteFor($student, $skill)
            : null;

        $studentSkill = $outcome['student_skill'];

        return response()->json([
            'is_correct' => $outcome['is_correct'],
            'explanation_ar' => $outcome['explanation_ar'],
            // Present only when the chosen distractor maps to a known error — and it maps because
            // the distractor was generated by executing that error, not because someone labelled it.
            'misconception' => $outcome['misconception'],
            'next_difficulty' => $decision->difficulty->value,
            'action' => $decision->action->value,
            'route_to' => $prerequisite === null ? null : [
                'skill_code' => $prerequisite->code,
                'name_ar' => $prerequisite->name_ar,
            ],
            'skill' => [
                'code' => $skill->code,
                'mastery_score' => $studentSkill->mastery_score,
                'status' => $studentSkill->status->value,
                'attempts' => $studentSkill->attempts,
                'hard_correct' => $studentSkill->hard_correct,
            ],
        ]);
    }
}
