<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\UserRole;
use App\Models\Classroom;
use App\Models\Question;
use App\Models\QuestionOption;
use App\Models\Skill;
use App\Models\Student;
use App\Models\User;
use App\Services\ExerciseService;
use App\Services\MasteryService;
use App\Services\RecoveryPathService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * The classroom a judge opens.
 *
 * Every figure it produces is generated by driving the REAL services, one answer at a time — the
 * same code path a child's phone uses. Nothing is written straight into student_skills. So the
 * mastery scores, the Elo drift and the misconception counts on the teacher dashboard are all
 * genuine consequences of genuine answers, and a judge who checks the arithmetic finds it holds.
 *
 * Deterministic: a fixed seed, so the demo shows the same classroom every night.
 */
final class DemoSeeder extends Seeder
{
    public const TEACHER_EMAIL = 'teacher@nabd.demo';

    public const ADMIN_EMAIL = 'admin@nabd.demo';

    public const PASSWORD = 'nabd-demo';

    /** Chosen by hand rather than generated. A judge has to be able to type it from a slide. */
    public const JOIN_CODE = 'NABD26';

    private int $seed = 20260826;

    public function run(): void
    {
        if (Skill::query()->doesntExist()) {
            $this->call(CurriculumSeeder::class);
        }

        DB::transaction(function (): void {
            $teacher = $this->staff();
            $classroom = $this->classroom($teacher);

            $this->confidentStudents($classroom);
            $this->stuckOnOneSkill($classroom);
            $this->sharingOneMisconception($classroom);
            $this->tryingHardAndNotMoving($classroom);
            $this->justArrived($classroom);
        });
    }

    private function staff(): User
    {
        User::updateOrCreate(
            ['email' => self::ADMIN_EMAIL],
            ['name' => 'مشرف نبض', 'password' => self::PASSWORD, 'role' => UserRole::Admin],
        );

        return User::updateOrCreate(
            ['email' => self::TEACHER_EMAIL],
            [
                'name' => 'أ. سمية',
                'password' => self::PASSWORD,
                'role' => UserRole::Teacher,
                'school_name' => 'مركز تعليمي — غزة',
            ],
        );
    }

    private function classroom(User $teacher): Classroom
    {
        return Classroom::updateOrCreate(
            ['join_code' => self::JOIN_CODE],
            ['teacher_id' => $teacher->id, 'name' => 'صف سابع — أ', 'grade' => 7],
        );
    }

    /**
     * Marks everything up to a ceiling as mastered — what a completed diagnostic would have found.
     *
     * Without this every demo student's path starts at primary-school place value, which is
     * technically correct for someone with no recorded mastery and tells exactly the wrong story:
     * the whole claim is that the path starts at a student's REAL gap, not at the bottom.
     */
    private function establishBaseline(Student $student, string $ceilingCode): void
    {
        $ceiling = Skill::query()->where('code', $ceilingCode)->value('order_index');

        if ($ceiling === null) {
            return;
        }

        $mastered = Skill::query()
            ->where('order_index', '<=', $ceiling)
            ->where('grade_level', '<=', $student->grade)
            ->pluck('code')
            ->all();

        app(MasteryService::class)->applyDiagnostic($student, $mastered, []);
    }

    /** Students rebuilding fractions and getting there. */
    private function confidentStudents(Classroom $classroom): void
    {
        foreach (['ليان', 'كرم', 'سما'] as $name) {
            $student = $this->student($classroom, $name);
            $this->establishBaseline($student, 'FRC.EQUIV');
            $this->practise($student, 'FRC.ADD.LIKE', correct: 9, wrong: 1);
            $this->buildPath($student, 'FRC.ADD.UNLIKE');
        }
    }

    /**
     * Four students stalled on the same skill.
     *
     * This is what the teacher's smart grouping is for: not four separate problems to chase, but
     * one twenty-minute session for four children who need the same thing.
     */
    private function stuckOnOneSkill(Classroom $classroom): void
    {
        foreach (['أحمد', 'يوسف', 'زيد', 'مريم'] as $name) {
            $student = $this->student($classroom, $name);
            $this->establishBaseline($student, 'OPS.DIV.BASIC');
            $this->practise($student, 'OPS.DIV.LONG', correct: 2, wrong: 6);
            $this->buildPath($student, 'FRC.ADD.UNLIKE');
        }
    }

    /**
     * Three students who keep choosing the SAME wrong answer.
     *
     * Not "three students failed fractions" — three students adding numerator to numerator and
     * denominator to denominator. That is a twenty-minute fix, and it is invisible to any system
     * that records only a score.
     */
    private function sharingOneMisconception(Classroom $classroom): void
    {
        $skill = Skill::query()->where('code', 'FRC.ADD.UNLIKE')->first();

        if ($skill === null) {
            return;
        }

        $trapped = Question::query()
            ->where('skill_id', $skill->id)
            ->whereHas('options', fn ($q) => $q->whereHas(
                'misconception',
                fn ($m) => $m->where('tag', 'frc.add_across'),
            ))
            ->with('options.misconception')
            ->take(4)
            ->get();

        foreach (['جنى', 'محمود', 'رهف'] as $name) {
            $student = $this->student($classroom, $name);
            $this->establishBaseline($student, 'FRC.ADD.LIKE');

            foreach ($trapped as $question) {
                $trap = $question->options->first(
                    static fn (QuestionOption $o): bool => $o->misconception?->tag === 'frc.add_across',
                );

                if ($trap !== null) {
                    $this->answer($student, $question, $trap);
                }
            }

            $this->buildPath($student, 'FRC.ADD.UNLIKE');
        }
    }

    /**
     * One student who has done the work and is still not moving.
     *
     * The hardest case to see without data and the easiest to miss in a class of sixty: a child
     * who keeps trying, keeps failing, and never complains. Sixteen attempts at a low score is
     * effort without progress, which is the signal that more of the same will not help — and it is
     * the only entry on the dashboard that names one child rather than a group.
     */
    private function tryingHardAndNotMoving(Classroom $classroom): void
    {
        $student = $this->student($classroom, 'بلال');
        $this->establishBaseline($student, 'OPS.MUL.MULTI');
        $this->practise($student, 'OPS.DIV.LONG', correct: 3, wrong: 13);
        $this->buildPath($student, 'FRC.ADD.UNLIKE');
    }

    /** Two students who have logged in and done nothing yet — the empty state, on the real screen. */
    private function justArrived(Classroom $classroom): void
    {
        foreach (['بيان', 'عمر'] as $name) {
            $this->student($classroom, $name);
        }
    }

    /* ------------------------------------------------------------------ internals */

    private function student(Classroom $classroom, string $name): Student
    {
        return Student::updateOrCreate(
            ['classroom_id' => $classroom->id, 'display_name' => $name],
            [
                'grade' => $classroom->grade,
                'pin_hash' => '1234',
                'login_token' => Student::generateLoginToken(),
            ],
        );
    }

    /** Answers `correct` items right and `wrong` items wrong, through the real exercise service. */
    private function practise(Student $student, string $skillCode, int $correct, int $wrong): void
    {
        $skill = Skill::query()->where('code', $skillCode)->first();

        if ($skill === null) {
            return;
        }

        $exercises = app(ExerciseService::class);
        $script = $this->shuffleScript($correct, $wrong);

        foreach ($script as $shouldBeCorrect) {
            $question = $exercises->nextQuestion($student, $skill);

            if ($question === null) {
                return;
            }

            $option = $question->options->firstWhere('is_correct', $shouldBeCorrect);

            if ($option !== null) {
                $exercises->submit($student, $question, $option);
            }
        }
    }

    private function answer(Student $student, Question $question, QuestionOption $option): void
    {
        app(ExerciseService::class)->submit($student, $question, $option);
    }

    private function buildPath(Student $student, string $targetCode): void
    {
        $target = Skill::query()->where('code', $targetCode)->first();

        if ($target !== null) {
            app(RecoveryPathService::class)->generate($student, $target);
        }
    }

    /**
     * Interleaves right and wrong answers deterministically.
     *
     * Right-then-wrong in blocks would produce mastery scores skewed by the recency weighting and
     * a classroom that looks nothing like a real one.
     *
     * @return list<bool>
     */
    private function shuffleScript(int $correct, int $wrong): array
    {
        $script = [...array_fill(0, $correct, true), ...array_fill(0, $wrong, false)];

        for ($i = count($script) - 1; $i > 0; $i--) {
            $this->seed = ($this->seed * 1103515245 + 12345) & 0x7FFFFFFF;
            $j = $this->seed % ($i + 1);
            [$script[$i], $script[$j]] = [$script[$j], $script[$i]];
        }

        return $script;
    }
}
