<?php

declare(strict_types=1);

use App\Models\Classroom;
use App\Models\Student;
use App\Models\User;
use Database\Seeders\DemoSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;

uses(RefreshDatabase::class);

/**
 * The teacher's dashboard, against the demo classroom.
 *
 * That classroom is not fixture data: every figure in it was produced by answering questions one at
 * a time through the real ExerciseService. So these assertions are checking that the analytics
 * surface something true about genuine answers, not that a seeder wrote the numbers it was told to.
 */
function teacherOf(): array
{
    $teacher = User::query()->where('email', DemoSeeder::TEACHER_EMAIL)->firstOrFail();
    $classroom = Classroom::query()->where('join_code', DemoSeeder::JOIN_CODE)->firstOrFail();

    return [$teacher, $classroom, $teacher->createToken('staff')->plainTextToken];
}

function overview(): array
{
    [, $classroom, $token] = teacherOf();

    return test()->withToken($token)
        ->getJson("/api/teacher/classrooms/{$classroom->id}")
        ->assertOk()
        ->json();
}

beforeEach(function (): void {
    app(DemoSeeder::class)->run();
});

it('lists the classes a teacher owns, and only those', function (): void {
    [$teacher, , $token] = teacherOf();

    $stranger = User::factory()->teacher()->create();
    Classroom::factory()->create(['teacher_id' => $stranger->id, 'grade' => 8]);

    $response = test()->withToken($token)->getJson('/api/teacher/classrooms')->assertOk();

    expect($response->json('classrooms'))->toHaveCount($teacher->classrooms()->count())
        ->and($response->json('classrooms.0.students_count'))->toBe(12);
});

it('assembles the whole dashboard in one response', function (): void {
    $data = overview();

    expect($data)->toHaveKeys(['classroom', 'students', 'groups', 'misconceptions', 'interventions'])
        ->and($data['students'])->toHaveCount(12)
        ->and($data['classroom']['join_code'])->toBe(DemoSeeder::JOIN_CODE);
});

/**
 * ⭐ The claim the product is built on.
 *
 * Not "students are failing fractions" — a named error, the children who make it, and what to say
 * to them. This only holds because the distractors were generated by executing the misconception,
 * so the tag is a fact about how the option was produced rather than a label added afterwards.
 */
it('names the error a group of students share, and who they are', function (): void {
    $data = overview();

    $shared = collect($data['misconceptions'])
        ->firstWhere('name_ar', 'جمع البسط مع البسط والمقام مع المقام');

    expect($shared)->not->toBeNull()
        ->and($shared['student_count'])->toBe(3)
        ->and($shared['occurrences'])->toBeGreaterThanOrEqual(3)
        ->and($shared['skill_code'])->toBe('FRC.ADD.UNLIKE')
        // The teacher is told what to do about it, not just that it happened.
        ->and($shared['remediation_ar'])->not->toBeEmpty()
        ->and(collect($shared['students'])->pluck('display_name'))
        ->toContain('جنى', 'محمود', 'رهف');
});

it('puts the misconception affecting the most students first', function (): void {
    $counts = collect(overview()['misconceptions'])->pluck('student_count')->all();

    expect($counts)->not->toBeEmpty()
        ->and($counts)->toBe(collect($counts)->sortDesc()->values()->all());
});

/**
 * One student making an error is a coincidence. Surfacing it as a group would fill the screen with
 * noise and bury the two entries that are worth a lesson.
 */
it('ignores an error only one student makes', function (): void {
    foreach (overview()['misconceptions'] as $entry) {
        expect($entry['student_count'])->toBeGreaterThanOrEqual(2);
    }
});

it('groups students by the skill they are stuck on, largest group first', function (): void {
    $groups = overview()['groups'];

    expect($groups)->not->toBeEmpty();

    $sizes = array_map(static fn (array $g): int => count($g['students']), $groups);
    expect($sizes)->toBe(collect($sizes)->sortDesc()->values()->all());

    // The four students the demo stalls on long division are one session, not four problems.
    $division = collect($groups)->firstWhere('skill_code', 'OPS.DIV.LONG');
    expect($division['students'])->toHaveCount(4);
});

/**
 * Effort without progress is the signal. Few attempts is not struggling — it is not having started,
 * and a list that conflates the two is a list a teacher scrolls past.
 */
it('flags only students who have tried hard and not moved', function (): void {
    foreach (overview()['interventions'] as $entry) {
        expect($entry['attempts'])->toBeGreaterThanOrEqual(12)
            ->and($entry['mastery_score'])->toBeLessThanOrEqual(45.0);
    }
});

it('refuses a teacher looking at a class that is not theirs', function (): void {
    $stranger = User::factory()->teacher()->create();
    $theirs = Classroom::factory()->create(['teacher_id' => $stranger->id, 'grade' => 8]);
    Student::factory()->inClassroom($theirs)->create();

    [, , $token] = teacherOf();

    test()->withToken($token)->getJson("/api/teacher/classrooms/{$theirs->id}")->assertStatus(404);
});

it('keeps students out of the teacher dashboard', function (): void {
    $student = Student::query()->firstOrFail();

    test()->withToken($student->createToken('student')->plainTextToken)
        ->getJson('/api/teacher/classrooms')
        ->assertStatus(403);
});

it('requires a token', function (): void {
    test()->getJson('/api/teacher/classrooms')->assertStatus(401);
});
