<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('questions', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('skill_id')->constrained()->cascadeOnDelete();
            $table->string('type', 16)->default('mcq');
            $table->string('difficulty', 8);

            // Calibrated by EloEngine as students answer. Orders candidate questions within a
            // skill; never participates in the mastery decision.
            $table->decimal('difficulty_elo', 8, 2)->default(1200);

            $table->text('stem_ar');

            // Math is stored apart from the Arabic prose and rendered in its own LTR run. Inline
            // it and the bidi algorithm reorders "2x + 3 = 11" as soon as an Arabic word sits
            // beside it — the expression reads backwards to the student.
            $table->string('expression')->nullable();

            $table->text('hint_ar')->nullable();
            $table->text('explanation_ar')->nullable();
            $table->timestamps();

            $table->index(['skill_id', 'difficulty']);
        });

        Schema::create('question_options', function (Blueprint $table): void {
            $table->id();
            $table->foreignId('question_id')->constrained()->cascadeOnDelete();
            $table->string('text_ar');
            $table->boolean('is_correct')->default(false);

            // What this particular wrong answer means. Populated because the distractor was
            // GENERATED by executing that misconception, so the link is a fact rather than a
            // label — which is the only reason the teacher dashboard can act on it.
            $table->foreignId('misconception_id')->nullable()->constrained()->nullOnDelete();

            $table->unsignedTinyInteger('position')->default(0);

            $table->index(['question_id', 'is_correct']);
            $table->index('misconception_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('question_options');
        Schema::dropIfExists('questions');
    }
};
