#!/usr/bin/env node
/**
 * Generates web/src/styles/tokens.css from design/tokens.json.
 *
 * The CSS is a build artifact — never hand-edit it. Change design/tokens.json, run this, and let
 * tools/check-contrast.mjs prove the result is still readable.
 *
 * Run: node tools/build-tokens.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = 'web/src/styles/tokens.css';
const tokens = JSON.parse(readFileSync('design/tokens.json', 'utf8'));

/** Comment keys carry rationale for humans reading tokens.json; they are not tokens. */
const isToken = ([key]) => !key.startsWith('_') && !key.startsWith('$');

const emit = (prefix, group, indent = '  ') =>
  Object.entries(group)
    .filter(isToken)
    .map(([key, value]) => `${indent}--nabd-${prefix}${key}: ${value};`)
    .join('\n');

const emitPalette = () =>
  Object.entries(tokens.palette)
    .flatMap(([family, steps]) =>
      Object.entries(steps).map(([step, hex]) => `  --nabd-${family}-${step}: ${hex};`),
    )
    .join('\n');

const css = `/* ------------------------------------------------------------------------------
 * NABD design tokens — GENERATED by tools/build-tokens.mjs from design/tokens.json.
 * Do not edit by hand. Every colour pair here is verified against WCAG 2.2 AA in CI
 * by tools/check-contrast.mjs, in both themes.
 * ---------------------------------------------------------------------------- */

:root {
  color-scheme: dark;

  /* raw palette — use the semantic tokens below in components, not these */
${emitPalette()}

  /* semantic: dark is the default theme, not an option.
     Most students share a low-end Android and study after dark on whatever charge is left;
     OLED battery saving and night readability are constraints here, not preferences.
     Light and auto are both reachable from the in-app toggle. */
${emit('', tokens.semantic.dark)}

  /* typography */
  --nabd-font-sans: ${tokens.typography.family.sans};
  --nabd-font-mono: ${tokens.typography.family.mono};
${emit('weight-', tokens.typography.weight)}
${emit('text-', tokens.typography.scale)}
${emit('leading-', tokens.typography.leading)}

  /* space */
${emit('space-', tokens.space)}

  /* radius */
${emit('radius-', tokens.radius)}

  /* size */
${emit('size-', tokens.size)}

  /* motion */
${emit('duration-', tokens.motion.duration)}
${emit('ease-', tokens.motion.easing)}

  /* elevation */
${emit('shadow-', tokens.elevation)}
}

:root[data-theme='light'] {
  color-scheme: light;
${emit('', tokens.semantic.light)}
}

/* Only 'auto' follows the operating system. The default stays dark on purpose. */
@media (prefers-color-scheme: light) {
  :root[data-theme='auto'] {
    color-scheme: light;
${emit('', tokens.semantic.light, '    ')}
  }
}

/* Motion is switched off by the OS accessibility setting AND by the in-app battery saver.
   Both paths must work offline, so neither depends on anything but a CSS variable. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --nabd-duration-fast: 0ms;
    --nabd-duration-base: 0ms;
    --nabd-duration-slow: 0ms;
    --nabd-duration-pulse: 0ms;
  }
}

:root[data-motion='off'] {
  --nabd-duration-fast: 0ms;
  --nabd-duration-base: 0ms;
  --nabd-duration-slow: 0ms;
  --nabd-duration-pulse: 0ms;
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css, 'utf8');

const count = (css.match(/--nabd-/g) ?? []).length;
console.log(`\n✅ ${OUT}`);
console.log(`   ${count} custom property declarations`);
console.log(`   themes: dark (default), light, auto\n`);
