#!/usr/bin/env node
/**
 * Generates web/src/styles/tokens.css from design/tokens.json.
 *
 * The CSS is a build artifact — never hand-edit it. Change design/tokens.json, run this, and let
 * tools/check-contrast.mjs prove the result is still readable.
 *
 * Run: node tools/build-tokens.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = 'web/src/styles/tokens.css';
const tokens = JSON.parse(readFileSync('design/tokens.json', 'utf8'));

/** Comment keys carry rationale for humans reading tokens.json; they are not tokens. */
const isToken = ([key]) => !key.startsWith('_') && !key.startsWith('$');

const emit = (prefix, group, indent = '  ') =>
  Object.entries(group)
    .filter(isToken)
    .map(([key, value]) => `${indent}--adrak-${prefix}${key}: ${value};`)
    .join('\n');

const emitPalette = () =>
  Object.entries(tokens.palette)
    .flatMap(([family, steps]) =>
      Object.entries(steps).map(([step, hex]) => `  --adrak-${family}-${step}: ${hex};`),
    )
    .join('\n');

const css = `/* ------------------------------------------------------------------------------
 * ADRAK design tokens — GENERATED by tools/build-tokens.mjs from design/tokens.json.
 * Do not edit by hand. Every colour pair here is verified against WCAG 2.2 AA in CI
 * by tools/check-contrast.mjs, in both themes.
 * ---------------------------------------------------------------------------- */

:root {
  color-scheme: light;

  /* raw palette — use the semantic tokens below in components, not these */
${emitPalette()}

  /* semantic: light is the default.
     This is a reversal — dark was the default first, argued from OLED battery saving on the
     shared low-end Androids these students study on after sunset. Light replaced it because a
     session here is sustained reading of worked mathematics, and because the brand mark is
     light-ground artwork whose navy path loses its contrast on a dark surface entirely.
     The battery cost of that reversal is real and is not pretended away.
     Dark stays fully defined below and is one attribute away. */
${emit('', tokens.semantic.light)}

  /* typography */
  --adrak-font-sans: ${tokens.typography.family.sans};
  --adrak-font-mono: ${tokens.typography.family.mono};
${emit('weight-', tokens.typography.weight)}
${emit('text-', tokens.typography.scale)}
${emit('leading-', tokens.typography.leading)}

  /* space */
${emit('space-', tokens.space)}

  /* radius */
${emit('radius-', tokens.radius)}

  /* size */
${emit('size-', tokens.size)}

  /* motion */
${emit('duration-', tokens.motion.duration)}
${emit('ease-', tokens.motion.easing)}

  /* elevation */
${emit('shadow-', tokens.elevation)}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${emit('', tokens.semantic.dark)}
}

/* Only 'auto' follows the operating system. The default stays light on purpose. */
@media (prefers-color-scheme: dark) {
  :root[data-theme='auto'] {
    color-scheme: dark;
${emit('', tokens.semantic.dark, '    ')}
  }
}

/* Motion is switched off by the OS accessibility setting AND by the in-app battery saver.
   Both paths must work offline, so neither depends on anything but a CSS variable. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --adrak-duration-fast: 0ms;
    --adrak-duration-base: 0ms;
    --adrak-duration-slow: 0ms;
    --adrak-duration-pulse: 0ms;
  }
}

:root[data-motion='off'] {
  --adrak-duration-fast: 0ms;
  --adrak-duration-base: 0ms;
  --adrak-duration-slow: 0ms;
  --adrak-duration-pulse: 0ms;
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css, 'utf8');

const count = (css.match(/--adrak-/g) ?? []).length;
console.log(`\n✅ ${OUT}`);
console.log(`   ${count} custom property declarations`);
console.log(`   themes: light (default), dark, auto\n`);
