<?php

declare(strict_types=1);

namespace App\Services;

use App\Engine\MasteryStatus;
use App\Models\Classroom;
use Illuminate\Support\Facades\DB;

/**
 * What a teacher needs to know before the next lesson.
 *
 * The design constraint is a teacher with sixty students, two hours of electricity and no time to
 * interpret a chart. Every figure here has to point at an action: which four children to sit
 * together, which twenty-minute explanation fixes the most, which one child has stopped moving.
 *
 * Aggregates are read from the derived tables rather than replayed from the attempt log — a
 * dashboard that takes eight seconds on a five-year-old laptop is a dashboard nobody opens.
 */
final class TeacherAnalyticsService
{
    /**
     * Below this a shared misconception is a coincidence, not a lesson plan. Above it, the teacher
     * is looking at something worth twenty minutes of the whole group's time.
     */
    private const MIN_STUDENTS_FOR_GROUP = 2;

    /** @return list<array<string, mixed>> */
    public function roster(Classroom $classroom): array
    {
        $rows = DB::table('students')
            ->leftJoin('student_skills', 'student_skills.student_id', '=', 'students.id')
            ->where('students.classroom_id', $classroom->id)
            ->groupBy('students.id', 'students.display_name', 'students.grade', 'students.last_seen_at')
            ->select([
                'students.id',
                'students.display_name',
                'students.grade',
                'students.last_seen_at',
                DB::raw("SUM(CASE WHEN student_skills.status = 'mastered' THEN 1 ELSE 0 END) as mastered"),
                DB::raw("SUM(CASE WHEN student_skills.status = 'learning' THEN 1 ELSE 0 END) as learning"),
            ])
            ->orderBy('students.display_name')
            ->get();

        return $rows->map(static fn ($row): array => [
            'id' => (int) $row->id,
            'display_name' => $row->display_name,
            'grade' => (int) $row->grade,
            'mastered' => (int) $row->mastered,
            'learning' => (int) $row->learning,
            'last_seen_at' => $row->last_seen_at,
        ])->all();
    }

    /**
     * Students grouped by the skill they are stuck on.
     *
     * Not sixty individual problems to chase — a handful of sessions, each for the children who
     * need the same thing. This is the single most useful thing the data can produce for someone
     * teaching a class this size with this little time.
     *
     * @return list<array<string, mixed>>
     */
    public function smartGroups(Classroom $classroom): array
    {
        $rows = DB::table('student_skills')
            ->join('students', 'students.id', '=', 'student_skills.student_id')
            ->join('skills', 'skills.id', '=', 'student_skills.skill_id')
            ->where('students.classroom_id', $classroom->id)
            ->where('student_skills.status', MasteryStatus::Learning->value)
            ->select([
                'skills.code',
                'skills.name_ar',
                'skills.grade_level',
                'students.id as student_id',
                'students.display_name',
                'student_skills.mastery_score',
                'student_skills.attempts',
            ])
            ->orderBy('skills.order_index')
            ->orderBy('students.display_name')
            ->get();

        $groups = [];

        foreach ($rows as $row) {
            $groups[$row->code] ??= [
                'skill_code' => $row->code,
                'name_ar' => $row->name_ar,
                'grade_level' => (int) $row->grade_level,
                'students' => [],
            ];

            $groups[$row->code]['students'][] = [
                'id' => (int) $row->student_id,
                'display_name' => $row->display_name,
                'mastery_score' => (float) $row->mastery_score,
                'attempts' => (int) $row->attempts,
            ];
        }

        $groups = array_values($groups);

        // Largest first: a teacher with twenty minutes should see the session that reaches the most
        // children at the top of the screen, not have to scan for it.
        usort($groups, static fn (array $a, array $b): int => count($b['students']) <=> count($a['students']));

        return $groups;
    }

    /**
     * ⭐ The thing a score cannot tell a teacher.
     *
     * Not "twelve students are failing fractions" — twelve students adding numerator to numerator
     * and denominator to denominator. One is a problem that takes a term; the other is a
     * twenty-minute explanation, and it is invisible to any system that records only right and
     * wrong.
     *
     * This is only trustworthy because the distractors were GENERATED by executing the
     * misconception (see tools/questions/lib.mjs). The tag on an option is a fact about how that
     * option was produced, not a label somebody attached afterwards.
     *
     * @return list<array<string, mixed>>
     */
    public function misconceptions(Classroom $classroom): array
    {
        $rows = DB::table('exercise_attempts')
            ->join('misconceptions', 'misconceptions.id', '=', 'exercise_attempts.misconception_id')
            ->join('skills', 'skills.id', '=', 'exercise_attempts.skill_id')
            ->join('students', 'students.id', '=', 'exercise_attempts.student_id')
            ->where('students.classroom_id', $classroom->id)
            // Only approved entries reach a teacher. An unreviewed AI proposal presented as fact
            // would be exactly the unaccountable automation this product refuses.
            ->where('misconceptions.status', 'active')
            ->groupBy(
                'misconceptions.id',
                'misconceptions.name_ar',
                'misconceptions.remediation_ar',
                'misconceptions.source',
                'skills.code',
                'skills.name_ar',
            )
            ->select([
                'misconceptions.id',
                'misconceptions.name_ar',
                'misconceptions.remediation_ar',
                'misconceptions.source',
                'skills.code as skill_code',
                'skills.name_ar as skill_name_ar',
                DB::raw('COUNT(DISTINCT exercise_attempts.student_id) as student_count'),
                DB::raw('COUNT(*) as occurrences'),
            ])
            ->havingRaw('COUNT(DISTINCT exercise_attempts.student_id) >= ?', [self::MIN_STUDENTS_FOR_GROUP])
            ->orderByDesc('student_count')
            ->orderByDesc('occurrences')
            ->get();

        $students = $this->studentsByMisconception($classroom, $rows->pluck('id')->all());

        return $rows->map(static fn ($row): array => [
            'id' => (int) $row->id,
            'name_ar' => $row->name_ar,
            'remediation_ar' => $row->remediation_ar,
            'source' => $row->source,
            'skill_code' => $row->skill_code,
            'skill_name_ar' => $row->skill_name_ar,
            'student_count' => (int) $row->student_count,
            'occurrences' => (int) $row->occurrences,
            'students' => $students[(int) $row->id] ?? [],
        ])->all();
    }

    /**
     * Children who have stopped moving.
     *
     * Deliberately narrow. A list of forty "at risk" students is a list a teacher scrolls past; a
     * list of three is a list they act on this afternoon.
     *
     * @return list<array<string, mixed>>
     */
    public function interventions(Classroom $classroom, int $minAttempts = 12, float $maxScore = 45.0): array
    {
        $rows = DB::table('student_skills')
            ->join('students', 'students.id', '=', 'student_skills.student_id')
            ->join('skills', 'skills.id', '=', 'student_skills.skill_id')
            ->where('students.classroom_id', $classroom->id)
            ->where('student_skills.status', MasteryStatus::Learning->value)
            // Many attempts AND a low score: effort without progress, which is the signal that
            // more of the same is not going to work. Few attempts is not struggling, it is not
            // having started.
            ->where('student_skills.attempts', '>=', $minAttempts)
            ->where('student_skills.mastery_score', '<=', $maxScore)
            ->select([
                'students.id as student_id',
                'students.display_name',
                'skills.code as skill_code',
                'skills.name_ar as skill_name_ar',
                'student_skills.attempts',
                'student_skills.mastery_score',
            ])
            ->orderBy('student_skills.mastery_score')
            ->get();

        return $rows->map(static fn ($row): array => [
            'student_id' => (int) $row->student_id,
            'display_name' => $row->display_name,
            'skill_code' => $row->skill_code,
            'skill_name_ar' => $row->skill_name_ar,
            'attempts' => (int) $row->attempts,
            'mastery_score' => (float) $row->mastery_score,
        ])->all();
    }

    /**
     * @param  list<int|string>  $misconceptionIds
     * @return array<int, list<array{id: int, display_name: string}>>
     */
    private function studentsByMisconception(Classroom $classroom, array $misconceptionIds): array
    {
        if ($misconceptionIds === []) {
            return [];
        }

        $rows = DB::table('exercise_attempts')
            ->join('students', 'students.id', '=', 'exercise_attempts.student_id')
            ->where('students.classroom_id', $classroom->id)
            ->whereIn('exercise_attempts.misconception_id', $misconceptionIds)
            ->distinct()
            ->select([
                'exercise_attempts.misconception_id',
                'students.id',
                'students.display_name',
            ])
            ->orderBy('students.display_name')
            ->get();

        $grouped = [];

        foreach ($rows as $row) {
            $grouped[(int) $row->misconception_id][] = [
                'id' => (int) $row->id,
                'display_name' => $row->display_name,
            ];
        }

        return $grouped;
    }
}
